"""Static, explicitly labeled examples for the dashboard integration foundation."""


def get_conditions() -> dict:
    return {
        "location": "Pune",
        "temperature": 28.5,
        "humidity": 72,
        "rainfall": 12.4,
        "air_quality": 86,
        "updated_at": None,
        "demo": True,
        "source": "Static demonstration values; not live conditions.",
    }


def get_predictions() -> dict:
    return {
        "demo": True,
        "source": "Illustrative records only; no ML model is connected.",
        "items": [
            {
                "location": "Pune",
                "latitude": 18.5204,
                "longitude": 73.8567,
                "risk_type": "flood",
                "risk_score": 0.82,
                "risk_level": "HIGH",
            }
        ],
    }


def get_risks() -> dict:
    return {
        "demo": True,
        "source": "Static examples only; not real risk assessments.",
        "items": [
            {
                "location": "Pune",
                "risk_type": "flood",
                "risk_score": 0.82,
                "risk_level": "HIGH",
            },
            {
                "location": "Pune",
                "risk_type": "drought",
                "risk_score": 0.24,
                "risk_level": "LOW",
            },
            {
                "location": "Pune",
                "risk_type": "heatwave",
                "risk_score": 0.56,
                "risk_level": "MEDIUM",
            },
            {
                "location": "Delhi",
                "risk_type": "air_quality",
                "risk_score": 0.78,
                "risk_level": "HIGH",
            },
        ],
    }


def get_alerts() -> dict:
    return {
        "demo": True,
        "source": "Static demonstration alert; not live and not generated by monitoring.",
        "items": [
            {
                "id": "alert-001",
                "location": "Delhi",
                "risk_type": "air_quality",
                "risk_level": "HIGH",
                "message": "High air-quality risk detected.",
                "severity": "HIGH",
            }
        ],
    }
