/**
 * ClimateSense AI — Centralized Constants & Development/Demo Data Layer.
 *
 * NOTE: All mock values in DEV_DATA are isolated baseline fixtures.
 * They will be seamlessly replaced by live API responses from ClimateSense AI Backend (/api/v1).
 */

export const APP_NAME = 'ClimateSense AI';
export const APP_SUBTITLE = 'AI-Powered Climate Intelligence & Early Warning System';

export const RISK_LEVELS = {
  LOW: { label: 'Low', color: '#10b981', bg: 'rgba(16, 185, 129, 0.12)', border: 'rgba(16, 185, 129, 0.3)' },
  MODERATE: { label: 'Moderate', color: '#f59e0b', bg: 'rgba(245, 158, 11, 0.12)', border: 'rgba(245, 158, 11, 0.3)' },
  HIGH: { label: 'High', color: '#f97316', bg: 'rgba(249, 115, 22, 0.12)', border: 'rgba(249, 115, 22, 0.3)' },
  CRITICAL: { label: 'Critical', color: '#ef4444', bg: 'rgba(239, 68, 68, 0.12)', border: 'rgba(239, 68, 68, 0.3)' },
  SEVERE: { label: 'Severe', color: '#ef4444', bg: 'rgba(239, 68, 68, 0.12)', border: 'rgba(239, 68, 68, 0.3)' },
};

export const DEV_DATA = {
  weather: {
    location: 'Central Capital Station (Dev/Test)',
    latitude: 28.6139,
    longitude: 77.2090,
    temperature: 29.5,
    humidity: 62.0,
    rainfall: 14.2,
    wind_speed: 18.5,
    pressure: 1012.3,
    timestamp: '2026-09-30T16:30:00Z',
  },
  aqi: {
    location: 'Central Capital Station (Dev/Test)',
    latitude: 28.6139,
    longitude: 77.2090,
    aqi: 165,
    pm25: 78.4,
    pm10: 142.1,
    no2: 34.6,
    so2: 12.1,
    co: 1.8,
    o3: 45.2,
    timestamp: '2026-09-30T16:30:00Z',
  },
  overallRisk: {
    location: 'National Capital Region (Dev/Test)',
    overall_risk_level: 'High',
    overall_risk_score: 60.5,
    flood_risk: 78.0,
    drought_risk: 22.0,
    heatwave_risk: 54.0,
    air_quality_risk: 72.0,
    timestamp: '2026-09-30T16:30:00Z',
  },
  risks: [
    {
      hazard: 'Flood Risk',
      id: 'flood',
      risk_level: 'High',
      risk_score: 78,
      indicator: 'Rainfall & drainage accumulation',
      icon: '🌊',
    },
    {
      hazard: 'Drought Risk',
      id: 'drought',
      risk_level: 'Low',
      risk_score: 22,
      indicator: 'Adequate regional soil moisture',
      icon: '☀️',
    },
    {
      hazard: 'Heatwave Risk',
      id: 'heatwave',
      risk_level: 'Moderate',
      risk_score: 54,
      indicator: 'Weekly thermal anomaly trends',
      icon: '🔥',
    },
    {
      hazard: 'Air Quality Risk',
      id: 'air_quality',
      risk_level: 'High',
      risk_score: 72,
      indicator: 'Inversion layer particle concentration',
      icon: '💨',
    },
  ],
  predictions: [
    {
      hazard: 'flood',
      title: 'Hydrological Flood Inundation',
      location: 'Northern Drainage Basin',
      risk_level: 'High',
      risk_score: 0.78,
      prediction: 'Elevated flood risk due to forecasted antecedent precipitation (Dev/Test Baseline)',
      model: 'xgboost_flood_baseline (dev/test)',
      icon: '🌊',
      timestamp: '2026-09-30T16:30:00Z',
    },
    {
      hazard: 'drought',
      title: 'Agricultural Drought Index',
      location: 'Arid Outskirts',
      risk_level: 'Low',
      risk_score: 0.22,
      prediction: 'Normal soil moisture levels indicate minimal drought risk (Dev/Test Baseline)',
      model: 'random_forest_drought_baseline (dev/test)',
      icon: '☀️',
      timestamp: '2026-09-30T16:30:00Z',
    },
    {
      hazard: 'heatwave',
      title: 'Extreme Thermal Anomaly',
      location: 'Southern Industrial Belt',
      risk_level: 'Moderate',
      risk_score: 0.54,
      prediction: 'Moderate thermal anomaly detected in weekly trend (Dev/Test Baseline)',
      model: 'lstm_temperature_baseline (dev/test)',
      icon: '🔥',
      timestamp: '2026-09-30T16:30:00Z',
    },
    {
      hazard: 'air_quality',
      title: 'Atmospheric PM2.5 Accumulation',
      location: 'Metropolitan Core',
      risk_level: 'High',
      risk_score: 0.72,
      prediction: 'Particulate accumulation expected under low boundary layer conditions (Dev/Test Baseline)',
      model: 'ensemble_aqi_baseline (dev/test)',
      icon: '💨',
      timestamp: '2026-09-30T16:30:00Z',
    },
  ],
  mapZones: [
    {
      id: 'zone-01',
      name: 'Central Monitoring Zone (Dev/Test)',
      hazard: 'Air Quality',
      risk_level: 'High',
      risk_score: 74.2,
      coordinates: [77.2090, 28.6139],
      details: 'AQI 165 • Low wind ventilation • High vehicle density',
    },
    {
      id: 'zone-02',
      name: 'Northern Drainage Basin (Dev/Test)',
      hazard: 'Flood',
      risk_level: 'Severe',
      risk_score: 82.5,
      coordinates: [77.1025, 28.7041],
      details: 'Soil saturation 85% • Riverbank runoff advisory',
    },
    {
      id: 'zone-03',
      name: 'Southern Industrial Belt (Dev/Test)',
      hazard: 'Heatwave',
      risk_level: 'Moderate',
      risk_score: 58.0,
      coordinates: [77.3178, 28.4089],
      details: 'Surface Temp 38.4°C • Urban heat island effect',
    },
  ],
  alerts: [
    {
      id: 'alert-fl-001',
      hazard: 'flood',
      severity: 'High',
      title: 'Flash Flood Advisory',
      message: 'Heavy rainfall forecast exceeding 100mm in 24 hours. Low-lying zones should prepare drainage mitigations.',
      location: 'Northern Catchment Area',
      timestamp: '2026-09-30 22:00 UTC',
      active: true,
    },
    {
      id: 'alert-aq-002',
      hazard: 'air_quality',
      severity: 'Severe',
      title: 'Poor Air Quality Alert',
      message: 'PM2.5 index exceeds unhealthy threshold. Sensitive individuals are advised to reduce outdoor exertion.',
      location: 'Metropolitan Core',
      timestamp: '2026-09-30 22:00 UTC',
      active: true,
    },
    {
      id: 'alert-hw-003',
      hazard: 'heatwave',
      severity: 'Moderate',
      title: 'Thermal Spike Advisory',
      message: 'Surface temperature projected to exceed 38°C in industrial sectors.',
      location: 'Southern Industrial Belt',
      timestamp: '2026-09-30 22:00 UTC',
      active: true,
    },
  ],
};
